version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - SECRET_KEY=samplesecret123
      - DEBUG=True
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
