version: "3"
services:
  web:
    # build: .
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - SECRET_KEY=samplesecret123
      - DEBUG=True
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
